### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Yurii-Solodovnyk** [Yurii-Solodovnyk/Portfolio#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Yuriy-Solodovnik-j** [comment]
You need do describe some basic information. I am a hardworking, disciplined, responsible and organized person. No work experience in companies, but with a great desire. Always open to new things and knowledge.

**Comment by Yurii-Solodovnyk** [comment]
Thanks
