### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Yurii-Solodovnyk** [Yurii-Solodovnyk/Portfolio#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Yuriy-Solodovnik-j** [comment]
linkedin.com/in/yuriy-solodovnik
https://www.facebook.com/yuriy.solodovnikk
mail - yurii.solodovnyk@nure.ua
tel - +380505529359
