### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Yurii-Solodovnyk** [Yurii-Solodovnyk/Portfolio#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Yuriy-Solodovnik-j** [comment]
07.19.2001 - Born in the town of Lozovaya.
2003-2007 - Spent in kindergarten like an ordinary child
2007-2018 - Studied at Panyutinskaya school №1
2018 - now - Student of Kharkiv National University of Radio Electronics. Faculty of Computer Engineering and Management, specialty Computer Engineering (not to be confused with the name of the faculty).
