### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Yurii-Solodovnyk** [Yurii-Solodovnyk/Portfolio#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Yuriy-Solodovnik-j** [comment]
LANGUAGES
us ENGLISH(Intermediate) ua УКРАЇНСЬКА(Native) ru РУССКИЙ(Native).

SKILLS
Base Front End technologies: HTML5, CSS3, JavaScript. Good knowledge of C#, WinForms. Basic knowledge of databases, MySQL, Oracle, MS SQL. Some work experience with PHP, Python with Django, C++, Java.

CHARACTER
DISCIPLINED CONSCIENTIOUS RATIONAL CURIOUS LOW-EMOTIONAL CALM STUBBORN COMPETITIVE

LIKES 😃
GOOD FOOD BAD FOOD FOOTBALL VOLLEYALL BASLETBALL RUNNING ROCK DOGS TRAVELING FILMS

DISLIKES 😞
ARROGANT PEOPLE INJUSTICE ANNOYANCE BALD CATS DRUGS HYPOCRISY

WANTS 🥺
START MY OWN SOFTWARE DEVELOPMENT COMPANY, BE A PROFESSIONAL IN MY FIELD, BE A WELL EDUCATED PERSON
